name: Deploy Website

on:
  push:
    branches:
      - master # Action will trigger ehen changes are pushed to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Linux-based virtual machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Gets the repository files

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch where Github Pages serves the site, Guess who the user was...
          folder: . # Deploy everything in the repository root
